platform :ios, '17.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PB_FIELD_32BIT=1'
      ]
      # Fix for Firebase module conflicts
      config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
    end
  end
end

target 'TheNileKartApp' do
  use_modular_headers!
  
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
end
